name: citizen_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  pdf: ^1.9.0
  path_provider: ^1.6.11
  printing: ^3.5.0
  path: 1.6.4
  image_picker: ^0.6.7+4
  flutter_full_pdf_viewer: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

  assets:
    - assets/img/
